spring:
  application:
    name: microservice-trainer
  config:
    import: optional:configserver:http://localhost:8888
feign:
  okhttp:
    enabled=true

management:
  server:
    port: 9091

springdoc:
  swagger-ui.path: /swagger-ui.html