spring:
  application:
    name: microservice-pokedex
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATABASE_URL}/pokedex
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

management:
  server:
    port: 9090

springdoc:
  swagger-ui.path: /swagger-ui.html

