spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always # Mostrar detalles en el endpoint de salud
  security:
    enabled: false # Deshabilitar la seguridad de Actuator (para entorno de desarrollo)

logging:
  level:
    org:
      springframework:
        cloud: DEBUG