server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: trainers
          uri: http://localhost:7080
          predicates:
            - Path=/api/v1/trainer/**
        - id: pokedex
          uri: http://localhost:7090
          predicates:
            - Path=/api/v1/pokedex/**
        - id: pokemonfound
          uri: http://localhost:7090
          predicates:
            - Path=/api/v1/pokemonfound/**

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: true