server:
  port: 7080

spring:
  application:
    name: microservice-trainer
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATABASE_URL}/pokedex
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: "*"